### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by Octember**

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by Octember** [comment]
Just signed :)

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by fredemmott** [comment]
We post-process the markdown; this fixes them in github, but breaks them when the site is built - see https://docs.hhvm.com/hhvm/basic-usage/introduction

**Comment by fredemmott** [comment]
(we also don't want adding/removing/renumbering sections to require content edits)

**Pull request closed without merging**
