### PR TITLE
add example for as

### PR DESCRIPTION
**Pull request by andrewjtimmons**
### What
This resolves https://github.com/hhvm/user-documentation/issues/800

I followed this guide
https://github.com/hhvm/user-documentation/blob/master/CONTRIBUTING.md#testing-changes

### Testing

`$ hhvm guides/hack/11-built-in-types/34-enumerated-types-examples/As.php`
runs cleanly

It looks ok when I build the site 
image

I am having trouble running some of the prescribed tests
`vendor/bin/hacktest tests/` is failing for me, even on the master branch with no changes.

The output is rather long, but ends up at
```

2283) HHVM\UserDocumentation\Tests\AutoLinkifyAPITest::testAutoLinkify with data set #Default Namespace
Call to undefined function HH\Lib\Experimental\OS\_Private\throw_errno()

3 /Users/atimmons/user-documentation/tests/AutoLinkifyAPITest.php(-1): HHVM\UserDocumentation\Tests\PageLoader::getPageAsync()

Fatal error: Uncaught Error: Call to undefined function HH\Lib\Math\sum() in /Users/atimmons/user-documentation/vendor/hhvm/hacktest/src/_Private/CLIOutputHandler.hack:-1
Stack trace:
#0 /Users/atimmons/user-documentation/vendor/hhvm/hacktest/src/_Private/ConciseCLIOutput.hack(-1): Facebook\HackTest\_Private\CLIOutputHandler->writeSummaryAsync()
#1 /Users/atimmons/user-documentation/vendor/hhvm/hacktest/src/_Private/CLIOutputHandler.hack(-1): Facebook\HackTest\_Private\ConciseCLIOutput->writeProgressImplAsync()
#2 /Users/atimmons/user-documentation/vendor/hhvm/hacktest/src/HackTestCLI.hack(-1): Facebook\HackTest\_Private\CLIOutputHandler->writeProgressAsync()
#3 /Users/atimmons/user-documentation/vendor/hhvm/hacktest/src/ProgressEvent.hack(-1): Closure$Facebook\HackTest\HackTestCLI::mainAsync#4()
#4 /Users/atimmons/user-documentation/vendor/hhvm/hacktest/src/_Private/OnScopeExitAsync.hack(-1): Closure$Facebook\HackTest\ProgressEvent::onScopeExit()
#5 /Users/atimmons/user-documentation/vendor/hhvm/hacktest/src/Runner/HackTestRunner.hack(-1): Facebook\HackTest\_Private\OnScopeExitAsync->__disposeAsync()
#6 /Users/atimmons/user-documentation/vendor/hhvm/hacktest/src/HackTestCLI.hack(-1): Facebook\HackTest\HackTestRunner::runAsync()
#7 /Users/atimmons/user-documentation/vendor/facebook/hh-clilib/src/CLIBase.hack(-1): Facebook\HackTest\HackTestCLI->mainAsync()
#8 /Users/atimmons/user-documentation/vendor/hhvm/hacktest/bin/hacktest.hack(-1): Facebook\CLILib\CLIBase::runAsync()
#9 /Users/atimmons/user-documentation/vendor/hhvm/hacktest/bin/hacktest(-1): Facebook\HackTest\hack_test_main_async()
#10 (): Facebook\HackTest\hack_test_main_async_UNSAFE()
#11 (): Closure$__SystemLib\enter_async_entry_point()
#12 (): HH\Asio\join()
#13 (): __SystemLib\enter_async_entry_point()
#14 {main}
```

It also dies for all tests when doing the run.php file.
```
$ hhvm api-sources/hhvm/hphp/test/run.php  guides/hack/11-built-in-types/34-enumerated-types-examples
Running 6 tests in 4 threads (0 in serial)

FAILED: guides/hack/11-built-in-types/34-enumerated-types-examples/Colors.php
001+ sh: /Users/atimmons/user-documentation/api-sources/hhvm/hphp/test/hphp/tools/timeout.sh: No such file or directory
001- 

FAILED: guides/hack/11-built-in-types/34-enumerated-types-examples/BitFlags.php
001+ sh: /Users/atimmons/user-documentation/api-sources/hhvm/hphp/test/hphp/tools/timeout.sh: No such file or directory
001- 

FAILED: guides/hack/11-built-in-types/34-enumerated-types-examples/Permission.php
001+ sh: /Users/atimmons/user-documentation/api-sources/hhvm/hphp/test/hphp/tools/timeout.sh: No such file or directory
001- 

FAILED: guides/hack/11-built-in-types/34-enumerated-types-examples/As.php
001+ sh: /Users/atimmons/user-documentation/api-sources/hhvm/hphp/test/hphp/tools/timeout.sh: No such file or directory
001- 

FAILED: guides/hack/11-built-in-types/34-enumerated-types-examples/enum-methods.php
001+ sh: /Users/atimmons/user-documentation/api-sources/hhvm/hphp/test/hphp/tools/timeout.sh: No such file or directory
001- Position::getNames() ---
002- 	key >0< has value >Top<
003- 	key >1< has value >Bottom<
004- 	key >2< has value >Left<
005- 	key >3< has value >Right<
006- 	key >4< has value >Center<
007- Position::getValues() ---
008- 	key >Top< has value >0<
009- 	key >Bottom< has value >1<
010- 	key >Left< has value >2<
011- 	key >Right< has value >3<
012- 	key >Center< has value >4<

FAILED: guides/hack/11-built-in-types/34-enumerated-types-examples/Positions.inc.php
001+ sh: /Users/atimmons/user-documentation/api-sources/hhvm/hphp/test/hphp/tools/timeout.sh: No such file or directory
001- 
```
`hhvm api-sources/hhvm/hphp/test/run.php guides/hack/11-built-in-types/` fails too, but I changed none of those files or tests

### CODE REVIEW

**Comment by andrewjtimmons** [comment]
RE the CLA the owner of Slack's CLA, Scott Sandler, emailed cla@fb.com

**Comment by fredemmott** [comment]
Thanks; you'll need to follow https://github.com/hhvm/user-documentation#building-the-site to install dependencies and build the site before tests are runnable

**Comment by andrewjtimmons** [comment]
Thank you Fred!

I think I did those steps correctly so I could see the site and my changes using the `Running The Site From A Checkout` instructions and the `Building The Site` instructions (see the screenshot of the local running site with my change in the first pr comment.

Here are the logs from a fresh run of those steps
```
$ hhvm bin/build.php

2020-02-07 15:01:03] BuildID
2020-02-07 15:01:04] Fetching API sources...
2020-02-07 15:01:04] ...not needed because the dependent step is being skipped.
2020-02-07 15:01:04] PHPIniSupportInHHVM
2020-02-07 15:01:04] Creating list of FB employee IP addresses...
2020-02-07 15:01:04] HHAPIDocBuildStep
2020-02-07 15:01:04] ...already built and no dependencies changed, skipping.
2020-02-07 15:01:04] PHPIniSupportInHHVMMarkdownBuild
2020-02-07 15:01:04] GuidesIndexBuild
2020-02-07 15:01:04] Finding sources in /Users/atimmons/user-documentation/guides....................................................................................................................................................................................
2020-02-07 15:01:05] UnifiedAPIIndexBuildStep
2020-02-07 15:01:05] Processing hack API Index
2020-02-07 15:01:06] Processing hsl API Index
2020-02-07 15:01:06] Processing hsl-experimental API Index
2020-02-07 15:01:06] Building Google Site Map
2020-02-07 15:01:07] APILegacyRedirectsBuild
2020-02-07 15:01:07] Processing old site index
2020-02-07 15:01:07] Cross-referencing with current site index.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
2020-02-07 15:01:07] Building Router-related codegen...
2020-02-07 15:01:13] Installing Ruby dependencies for SASS
2020-02-07 15:01:13] Building SASS
2020-02-07 15:01:14] StaticResourcesMapBuild
2020-02-07 15:01:14] Finding sources in /Users/atimmons/user-documentation/public...............
2020-02-07 15:01:14] GuidesHTMLBuild
2020-02-07 15:01:14] Finding sources in /Users/atimmons/user-documentation/guides....................................................................................................................................................................................
2020-02-07 15:01:14] Rendering markdown to HTML [fbgfm] ....................................................................................................................................................................................
2020-02-07 15:01:29] Creating summaries
2020-02-07 15:01:30] APIHTMLBuild
2020-02-07 15:01:30] Finding sources in /Users/atimmons/user-documentation/build/scratch/api-markdown (cached)
2020-02-07 15:01:30] Rendering markdown to HTML [fbgfm] ...............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
2020-02-07 15:01:42] UpdateAutoloaderBuildStep
```

```
$ hhvm api-sources/hhvm/hphp/test/run.php  guides/hack/11-built-in-types/34-enumerated-types-examples
Running 6 tests in 4 threads (0 in serial)

FAILED: guides/hack/11-built-in-types/34-enumerated-types-examples/Permission.php
001+ sh: /Users/atimmons/user-documentation/api-sources/hhvm/hphp/test/hphp/tools/timeout.sh: No such file or directory
001- 

FAILED: guides/hack/11-built-in-types/34-enumerated-types-examples/BitFlags.php
001+ sh: /Users/atimmons/user-documentation/api-sources/hhvm/hphp/test/hphp/tools/timeout.sh: No such file or directory
001- 

FAILED: guides/hack/11-built-in-types/34-enumerated-types-examples/Colors.php
001+ sh: /Users/atimmons/user-documentation/api-sources/hhvm/hphp/test/hphp/tools/timeout.sh: No such file or directory
001- 

FAILED: guides/hack/11-built-in-types/34-enumerated-types-examples/As.php
001+ sh: /Users/atimmons/user-documentation/api-sources/hhvm/hphp/test/hphp/tools/timeout.sh: No such file or directory
001- 

FAILED: guides/hack/11-built-in-types/34-enumerated-types-examples/enum-methods.php
001+ sh: /Users/atimmons/user-documentation/api-sources/hhvm/hphp/test/hphp/tools/timeout.sh: No such file or directory
001- Position::getNames() ---
002- 	key >0< has value >Top<
003- 	key >1< has value >Bottom<
004- 	key >2< has value >Left<
005- 	key >3< has value >Right<
006- 	key >4< has value >Center<
007- Position::getValues() ---
008- 	key >Top< has value >0<
009- 	key >Bottom< has value >1<
010- 	key >Left< has value >2<
011- 	key >Right< has value >3<
012- 	key >Center< has value >4<

FAILED: guides/hack/11-built-in-types/34-enumerated-types-examples/Positions.inc.php
001+ sh: /Users/atimmons/user-documentation/api-sources/hhvm/hphp/test/hphp/tools/timeout.sh: No such file or directory
001- 

6 tests failed
(╯°□°）╯︵ ┻━┻
```

**Comment by andrewjtimmons** [comment]
When I look for that file that is missing
```
001+ sh: /Users/atimmons/user-documentation/api-sources/hhvm/hphp/test/hphp/tools/timeout.sh: No such file or directory
```
It looks like something is missing after I build or not populating.
image

**Comment by fredemmott** [comment]
>  /Users/atimmons/user-documentation/api-sources/hhvm/hphp/test/hphp/tools/timeout.sh: No such file or directory

Something's gone pretty wrong here - do you have local modifications to api-sources/hhvm/hphp/test/run.php?

```
return __DIR__.'/../tools/timeout.sh';
```

That should resolve to `api-sources/hhvm/hphp/tools/timeout.sh` - but your path has an extra `hphp/test` in it

**Comment by fredemmott** [comment]
Sorry, I shouldn't have merged this yet, didn't see test status . reverting.

**Comment by andrewjtimmons** [comment]
Ah interesting.  Thank you for finding that issue.  `git diff` is showing nothing and `git stash` says no local changes to save, so I don't think I modified that file at the time I ran those tests.

I just went to that file and modified the help function to include the command you listed so it looks like this now
`var_dump(__DIR__.'/../tools/timeout.sh');`
```
function help() {
  $argv = \HH\global_get('argv');
  var_dump(__DIR__.'/../tools/timeout.sh');
  $ztestexample = 'test/zend/good/*/*z*.php'; // sep. for syntax highlighting.
  $help = <<<EOT
(redacted long paragraph of help text but it is here and still prints it)
```

When I run it I get
```
$ hhvm api-sources/hhvm/hphp/test/run.php --help
string(81) "/Users/atimmons/user-documentation/api-sources/hhvm/hphp/test/../tools/timeout.sh"
(+other normal help string about this is the hhm test-suite runner etc)
```

**Comment by fredemmott** [comment]
API-sources is ignored, so diff and status won’t show anything; it might be best to “git clean -ffdx” and start the setup again, from composer onwards

**Comment by andrewjtimmons** [comment]
I will try that, thank you

**Comment by andrewjtimmons** [comment]
Hmm still failing with the same results after clean and rebuild.  I see the git clean is failing to delete a few gems, but I am not certain those are related?
Compuser has some undefined funcs that look like php builtins, maybe something is missing there.

git_clean_output.txt](https://github.com/hhvm/user-documentation/files/4182351/git_clean_output.txt)
[test_output_fails.txt](https://github.com/hhvm/user-documentation/files/4182348/test_output_fails.txt)
[build.txt](https://github.com/hhvm/user-documentation/files/4182349/build.txt)
[composer_install.txt](https://github.com/hhvm/user-documentation/files/4182350/composer_install.txt)

**Pull request merged**
