### PR TITLE
Rewrite XHP one-liner

### PR DESCRIPTION
**Pull request by fredemmott**
I don't think 'XML' is a compelling advertisment nowadays :p

Also, Add missing '.' from shapes summary while I'm looking at this

### CODE REVIEW

**Comment by fredemmott** [comment]
cc @Swahvay - any better suggestions?

This shows up here: http://beta.docs.hhvm.com/hack/

**Comment by Swahvay** [comment]
Maybe something like: "Advanced UI rendering allowing HTML to be set directly in PHP and custom HTML elements to be defined." How about that?

**Comment by fredemmott** [comment]
IMO that's the biggest advantage of XHP over most other methods, but unless you've already been using it for a while, it's not clear why - so not the best 'advertisement'.

**Comment by SiebelsTim** [comment]
XSS safety and simplicity and/or extensibility is probably one of the best things to say considering advertisement.

**Comment by fredemmott** [comment]
@SiebelsTim : got some suggested text?

**Comment by SiebelsTim** [comment]
mhh. I'm really bad at this. 

---

I like emphasizing the *why* in contrast to the *how* better; which your text in this PR is doing already.

To be honest, having HTML inside of PHP is something PHP developers tried to avoid over the years and thus is not something that sounds appealing at first glance. You have to work with it or read some more about it to acknowledge its power. 

---
> Rendering HTML in a simple and extensible way that is XSS safe by default.

Meh.. I said I'm bad at this :P

**Comment by jwatzman** [comment]
Instead of components, something about *composable* components? Twig is really good at the rest -- templates, escaping, XSS, etc. Where every other templating language I've seen falls down is composability.

**Comment by Swahvay** [comment]
What about...

> An easily reusable and customizable UI system that automatically handles all escaping and XSS protection.

I say reusable instead of composable, simply because I think it's a little easier to understand. "Composable" is sort of an implementation adjective whereas I feel "reusable" is more of a relatable desire.

**Comment by fredemmott** [comment]
I'll probably go for that without 'all' - I don't want people to think `<script>{$foo}</script>` is safe.

**Comment by Swahvay** [comment]
Good point.

**Pull request closed without merging**
