### PR TITLE
Split out 00-overview/04-collections inline examples

### PR DESCRIPTION
**Pull request by daviddoran**
- `hh_client`
- `hhvm ../hhvm/hphp/test/run --hhvm-binary-path /usr/local/bin/hhvm guides/hack/00-overview/`
- http://127.0.0.1:8080/hack/overview/collections

After splitting out the inline examples I made some changes to make the code runnable:

- Use `int as int` or enum value can't be used to index into a Vector
- Move $opening_hours Vector into function (otherwise we'd need to use global)
- Add `?string` return typehint

Part of issue #60 

overview collections 2015-11-17 15-56-14
overview collections 2015-11-17 15-56-07
overview collections 2015-11-17 15-54-51
overview collections 2015-11-17 15-54-41
overview collections 2015-11-17 15-54-34

### CODE REVIEW

**Comment by JoelMarcey** [comment]
I am not sure why your merged pull requests are **not** counting as your commits @daviddoran :/

Still only shows you with 3 commits. https://github.com/hhvm/user-documentation/graphs/contributors

**Comment by JoelMarcey** [comment]
I see this: https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

**Comment by jwatzman** [comment]
I suspect that the email address you are committing with isn't attached to your github account, since your name isn't hyperlinked to your account on the commit log?

**Comment by daviddoran** [comment]
Thanks for the heads up. Just added my `@fb.com` and the commits seem to be showing up:

https://github.com/hhvm/user-documentation/commits?author=daviddoran

Hopefully the number on the "Contributors" page is just cached.

**Comment by JoelMarcey** [comment]
Yeah, we will give it some time to update. If it doesn't, there might be a way to get someone to force update it, as stated here: https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/

**Comment by JoelMarcey** [comment]
Yep. You are at 14 commits now! :+1:

**Comment by daviddoran** [comment]
Saw that, thanks for the nudge :smile:

**Pull request merged**
