### PR TITLE
Note on hack strict for Meta engineers

### PR DESCRIPTION
**Pull request by AndrewDiMola**
A note on hack strict, from internal feedback.

`Facebook` -> `Meta` refactor at a later date.

image

### CODE REVIEW

**Review by Wilfred — APPROVED** [review]
Looks good, but all files in Hack are strict now. `<?hh // strict` and `<?hh // partial` have no effect. The only way you can have a partial mode file is using the `.hackpartial` extension.

**Comment by AndrewDiMola** [comment]
> Looks good, but all files in Hack are strict now. `<?hh // strict` and `<?hh // partial` have no effect over `<?hh`. The only way you can have a partial mode file is using the `.hackpartial` extension.

Do you think it would be better to say... "All Hack source code at Meta should use the .php file extension and, by default, Hack Strict mode (with the plain <?hh header line)."

And also just add a general note on the existence of `.hackpartial`?

**Comment by Atry** [comment]
`Facebook Engineer?` vs `Meta Platforms Engineer?`

**Comment by AndrewDiMola** [comment]
> Facebook Engineer? -> Meta Engineer?

@Atry - I'm going to refactor this in a separate PR as there are a lot of file changes.

**Pull request merged**
