### PR TITLE
Skip mcrouter examples for \HH\Asio\ functions if McRouter extension not present

### PR DESCRIPTION
**Pull request by fredemmott**
Fails on MacOS

Planning to add testing of actual developer flow, so need clean test run
on all platforms :)

### CODE REVIEW

**Comment by fredemmott** [comment]
Related infra issues: #981, #982

**Review by jjergus — APPROVED** [review]
`\Hack\UserDocumentation\API\Examples\MCRouter\skipif()` checks that a server is running (so pretty much always fails, I don't think we have it set up anywhere), not just that the extension is present. Maybe we can have a separate one that just does

```hack
  if (!\extension_loaded('mcrouter') || !\extension_loaded('memcached')) {
    echo 'skip';
  }
```

(or just inline that here)?

**Comment by fredemmott** [comment]
I think we'll also need that here; once I've de-dockerized the testing a bit, we should look at adding mysql and memcached servers to the CI env

**Comment by fredemmott** [comment]
Rebased to merge the .skipif into the same commit

**Pull request merged**
