### PR TITLE
Implement display __Deprecated attributes

### LINKED ISSUE #129: Handle __Deprecated annotations

### PR DESCRIPTION
**Pull request by SiebelsTim**
fixes #129

### CODE REVIEW

**Comment by fredemmott** [comment]
Can you add something to the tests for this?

**Comment by SiebelsTim** [comment]
@fredemmott Do we have any tests for similar things? Such as if a method is static.

**Comment by fredemmott** [comment]
No, just that some example pages load; would still be good to add to APIPagesTest though.

**Comment by SiebelsTim** [comment]
Is this enough?

**Comment by simonwelsh** [comment]
This doesn't handle a sample rate set as part of the annotation.

**Comment by SiebelsTim** [comment]
I completely forgot about this one. This makes things easier as it is invalid to pass more than 2 and less than 1 parameter. So we only need the first parameter for the message.

**Pull request merged**
