### PR TITLE
fix description of Indexish

### PR DESCRIPTION
**Pull request by savil**
The previous description was more suitable for explaining what `arraykey` is.
Addresses issue #277, which i just filed.

### CODE REVIEW

**Comment by fredemmott** [comment]
This seems incorrect, or at least unclear, given:

```
[fredemmott@devbig349.prn1 ~/test] cat test.php
<?php

class Foo implements ArrayAccess {
  public function offsetGet($offset){}
  public function offsetSet($offset, $value){}
  public function offsetExists($offset){}
  public function offsetUnset($offset){}
}

var_dump((new Foo()) instanceof Indexish);
var_dump((new Foo()) instanceof HH\Indexish);
[fredemmott@devbig349.prn1 ~/test] hhvm test.php
bool(false)
bool(false)
```

**Comment by SiebelsTim** [comment]
@fredemmott Well, in Hack you can't really use ArrayAcces. Classes implementing ArrayAccess cannot be accessed with square brackets.

**Comment by fredemmott** [comment]
PHP interoperability is still a concern - this would imply that a Hack function taking indexish could be called with an arrayaccess implementation from PHP code.

**Comment by savil** [comment]
is the concern with the "square-bracket notation" part? Would amending that to "is anything that can be indexed into, like an array or collection" suffice?

**Comment by fredemmott** [comment]
Still inaccurate for arrayaccess.

**Comment by savil** [comment]
hmm okay, yeah, i haven't fully grokked the implications of needing to not imply this is ArrayAccess. I'm a tad lost on how to proceed. Do you agree the current wording is incorrect? Suggestions on how to fix it?

**Comment by fredemmott** [comment]
Yep, the current wording is currently incorrect. Right now we're leading towards what you have + "except for objects that implements ArrayAccess", though I'm trying to find out if there was a more consistent answer here.

The whole collections hierarchy is somewhat overcomplicated for what it does...

**Comment by fredemmott** [comment]
@savil : is there a plan here?

**Pull request merged**
