### PR TITLE
Tmp env variable

### PR DESCRIPTION
**Pull request by AndrewDiMola**
image

Probably should have it's own section with other important env variables? But it's a start?

### CODE REVIEW

**Review by fredemmott — CHANGES_REQUESTED** [review]
Environment variables need to be a separate section:
- in general, they need to modify `$_ENV`,  not `$_SERVER`
- this particular one is *only* used by the typechecker. HHVM settings have no effect on the typechecker. It must be set in the process environment.

**Comment by fredemmott** [comment]
Also, please squash merge commits when rebasing (git rebase -i is handy)

**Comment by AndrewDiMola** [comment]
yeah, you're right -- I can create a new PR that's more tidy.

**Comment by AndrewDiMola** [comment]
closing for a neater pr

**Pull request closed without merging**
