### PR TITLE
Add Pass by Value example (#879)

### PR DESCRIPTION
**Pull request by AndrewDiMola**
Explaining that lambas pass by value

### CODE REVIEW

**Comment by AndrewDiMola** [comment]
unresolved: should we reference https://docs.hhvm.com/hsl/reference/class/HH.Lib.Ref/?

**Comment by fredemmott** [comment]
> unresolved: should we reference https://docs.hhvm.com/hsl/reference/class/HH.Lib.Ref/?

yep :)

**Comment by fredemmott** [comment]
We have autolinking - hopefully this will 'just work':

```
If you need to mutate, use the HSL `Ref` class
```

... rather than needing to fully-qualify or specify the target page.

**Comment by AndrewDiMola** [comment]
> We have autolinking - hopefully this will 'just work':
> 
> ```
> If you need to mutate, use the HSL `Ref` class
> ```
> 
> ... rather than needing to fully-qualify or specify the target page.

worked on my local test!

**Review by fredemmott — APPROVED** [review]

**Comment by Wilfred** [comment]
@AndrewDiMola @jjergus  I don't think this is quite right.

```
$x = 5;
$f = $x ==> $x + 1;
$six = $f($x); // pass by value

echo($six); // result of 6
echo("\n");
echo($x); // $x is unchanged; result of 5
```

This example would also work with pass-by-reference, because `$f` isn't modifying anything.

There's two things we should probably cover:

(1) Variables are scoped to the function that they're assigned in.

```
$x = 1;
$f = () ==> { $x = 2; }
$f();

$x; // still 1
```

(2) Closures capture variables at the definition site, not the call site (unlike e.g. JS). (This is a subtlety I only learnt recently!)

```
$x = 1;
$f = () ==> { return $x; }
$x = 2;

$f(); // 1
```

**Comment by AndrewDiMola** [comment]
@Wilfred - Oh I see, in that example, I'm just getting the output of the function which of course is different but not demonstrating the modification behavior of the variable.

**Pull request merged**
