### PR TITLE
Improve hack documentation by adding examples for Math\mean

### PR DESCRIPTION
**Pull request by mmanuja-fb**
Task [T133748549](https://www.internalfb.com/intern/tasks/?t=133748549) 
screenshot of the in-terminal "links" browser:
image

### CODE REVIEW

**Comment by kunalb6** [comment]
Can you please add a screenshot from chrome/safari with the mean displayed as well?

**Comment by mmanuja-fb** [comment]
Screenshot from google chrome:
image

**Comment by kunalb6** [comment]
Can you please run the build commands documented here: https://www.internalfb.com/intern/opensource/ondemand/hhvm/user-documentation/

**Comment by mmanuja-fb** [comment]
Final screenshot after adding the output statement!
image

**Pull request merged**
