### PR TITLE
Fork 5 threads for rendering API

### PR DESCRIPTION
**Pull request by SiebelsTim**
The previous approach was too consuming and this is much more safe and
configurable.

We currently don't parse command line arguments, which could change number of
threads (and log level by the way). Let's do this sometimes later.

A downside to this is that it's more bulky in the code :(

### CODE REVIEW

**Comment by SiebelsTim** [comment]
After all, I have no idea what I'm doing. So could please someone have a look over this?

@JoelMarcey I think you are the only one not being on holiday and working on this repo, right? Additionally, you could test this with the amazon AWS Server :). So that we don't merge something non-functional

**Comment by JoelMarcey** [comment]
Another option to was to increase the RAM we use on AWS when we go into production. I think your other code may work fine then; that said, having something like this, which can be configurable (I wonder instead of hardcoding the threads if we can check and use the number of CPU cores - 1 as the number??). But maybe 5 is ok to start with.

I created a staging area for these type of changes so as not to bring down our production side, so we can test it.

cc @fredemmott

**Comment by SiebelsTim** [comment]
The other code will bomb your cpu though (with ~1400 tasks) and eventually start waiting to have time for this. Specifying threads is much nicer overall - on the deploying side and on the developer side.

**Comment by fredemmott** [comment]
I'm thinking I'm going to make md-render take file names on stdin and output progress on stdout, and use actual threads inside it. Should be more memory-efficient and probably faster even without the threading changes.

**Comment by SiebelsTim** [comment]
That's the best. :) What do you think? Close this then?

**Comment by fredemmott** [comment]
Might not need the threading, just re-using the process is a *huge* win: https://github.com/hhvm/user-documentation/commit/7dcf4a77ba5bbdcd6ba3dd06b1dfef7409092c28

**Pull request closed without merging**
