### PR TITLE
Support hhvm 4.47

### PR DESCRIPTION
**Pull request by lexidor**
- Needed to provide typehint on lambda, because of new inference.
 - Needed to add (string $\_, string $\_) typehint, because inference.
 guessed the type to be (string $\_, arraykey $\_).
 - Moved an HH_FIXME, in a lambda is used for type assertion (unsound).
 - Hack hhvm.hack_arr_compat_hack_arr_cmp_notices to the array test.

### CODE REVIEW

**Comment by fredemmott** [comment]
Was this via bin/update-versions ?

**Comment by lexidor** [comment]
No, I didn't know that was a thing. Now I know. I did this by hand. I'll run that script asap within the hour.

**Comment by fredemmott** [comment]
Thanks - see updating.md

> ` * @generated SignedSource<<4b188fcc0cbb2f5e658fe946e6e6a754>>`

This - in the tags file - should make this be a test failure that should be caught by CI. Will add to travis.sh

**Comment by fredemmott** [comment]
Good you rebase this to have:
- your manual changes to content as one commit
- the script run as another commit
- any fixes needed after the script run as another commit if needed (hopefully not)

Hard to review this as-is

**Pull request closed without merging**
