### PR TITLE
Add examples for Math and Str functions

### PR DESCRIPTION
**Pull request by saranicholas**

### CODE REVIEW

**Comment by saranicholas** [comment]
Screen Shot 2022-11-02 at 4 00 40 PM

**Comment by saranicholas** [comment]
Screen Shot 2022-11-02 at 4 18 30 PM

**Comment by saranicholas** [comment]
Screen Shot 2022-11-02 at 4 29 26 PM

**Comment by kunalb6** [comment]
thanks for adding this

**Pull request merged**
