### PR TITLE
Add fb-specific documentation link to 'Getting Started' page

### PR DESCRIPTION
**Pull request by fredemmott**
This guide covers how to set up various parts of the environment that
are automatically configured for FB engineers; it's not useful for them.

Test plan:

- opened page on localhost, saw nothing
- deleted `isNotFbViewer` class on body, saw text and link
- clicked link, got internal docs

### CODE REVIEW

**Comment by fredemmott** [comment]
Screen Shot 2019-12-16 at 10 16 21 AM

**Comment by azjezz** [comment]
Unless FACEBOOK is not planning on opening hack/hhvm for adoption outside FACEBOOK, I don't think this should go in public documentation.

I believe it should be the other way around. in FACEBOOK's private documentation : 
```
If you are working on an open source hack project, you want the [public](https://docs.hhvm.com) documentation.
```

**Comment by fredemmott** [comment]
These sections are only visible by default (without editing CSS) if you are connected from a Facebook corporate IP address (based on the ASN)

**Comment by fredemmott** [comment]
The primary reason for doing this is that if FB employees look at internal docs first instead, they will also *improve* the internal docs instead of improving the public docs.

**Comment by azjezz** [comment]
> The primary reason for doing this is that if FB employees look at internal docs first instead, they will also improve the internal docs instead of improving the public docs.

but here, this is pointing from public to internal, not internal to public.

+ why have 2 different docs ? won't merging the two make more sense ?

**Comment by fredemmott** [comment]
Language documentation is shared; the link documents:
- how to get a Facebook dev server using Facebook internal tools
- how to connect to it with Facebook’s IDE extensions
- how to add a page to facebook.com

It does not cover installation of Hack or HHVM. The FB content is not relevant externally, and the external content is not relevant internally.

**Comment by azjezz** [comment]
It doesn't make sense that someone would go to hhvm/hack documentation looking for something facebook.com specific, such as how to add a new route/page ( which, i agree, should have its own internal documentation )

but, if the internal documentation is the same as hhvm/user-documentation + facebook internal things, it should be split into its own.

so whether you do work at Facebook, or you are part of the community, there's only 1 place to go for hack/hhvm documentation, and learn/contribute.

**Comment by fredemmott** [comment]
> it should be split into its own.

This would require that the public docs be re-written in a facebook-specific markup language; if a new system internal system were made to avoid this, the content would be forked to the standard system. It would also *definitely* require moving the development workflow to an FB-internal source of truth (similar to the HSL); we do not sync entire repos from github on a regular basis, and the language is moving too fast for a manual process to be workable.

> so whether you do work at Facebook, or you are part of the community, there's only 1 place to go for hack/hhvm documentation, and learn/contribute.

This is the case for anything not fb-specific at present.

**Comment by fredemmott** [comment]
4a92e1a5

**Comment by jjergus** [comment]
We want FB people to consider docs.hhvm.com their primary source of documentation for Hack, because the more they use the site, the more likely they are to contribute improvements or at least report issues.

Historically this has been a big problem -- most FB people currently only look at internal documentation, and a lot of useful stuff ends up being only documented internally as a result.

I think it's reasonable to do changes like this if it helps us achieve that.

**Comment by fredemmott** [comment]
> Historically this has been a big problem -- most FB people currently only look at internal documentation, and a lot of useful stuff ends up being only documented internally as a result.

While docs.hhvm.com is meant to be the primary docs, there's some valuable internal docs as even with things as they are now, people still prefer to write things internally; I'll hopefully be publishing some of that soon - and  in those cases, I will be editing the internal docs to link here instead of duplicating

**Pull request closed without merging**
