### PR TITLE
Unify API and Guide nav implementations, use more appropriate data

### PR DESCRIPTION
**Pull request by fredemmott**
- removes the 'SideNav.js' entirely
 - JS is no longer aware of the structure of GroupsIndex or APIIndex (giving flexibiltiy to modify them to support search and redirects more easily)

Once this is merged, I'll split out some common stuff into xhp classes - eg `<navbar data={} currentItem={} />`

### CODE REVIEW

**Comment by fredemmott** [comment]
I'll also squash this a bit before landing.

**Comment by JoelMarcey** [comment]
@fredemmott Will this by default solve https://github.com/hhvm/user-documentation/issues/78

**Comment by fredemmott** [comment]
Nope, that should probably be sorted out in the index build step. I'll fix that separately and commit direct.

**Comment by fredemmott** [comment]
Here, have a rebase :p

**Comment by matthewjohnston4** [comment]
Perfect, looks good!

**Pull request merged**
